export interface Place {
  id: string;
  name: string;
  description: string;
  lat: number;
  lng: number;
  emoji: string;
  category: string;
  activityCategory: {
    main: (keyof typeof ACTIVITY_CATEGORIES)[];
  };
}

export interface Course {
  id: string;
  title: string;
  places: Place[];
  createdAt: Date;
  memo?: string;
  completed: boolean;
  category: 'date' | 'food' | 'tour' | 'workshop' | 'other';
  tags: string[];
  isPublic?: boolean;
  isFavorited?: boolean;
  favoriteCount?: number;
}

// 활동 카테고리 정의
export const ACTIVITY_CATEGORIES = {
  eating: {
    label: '먹기',
    emoji: '🍽️',
    color: 'bg-red-100 text-red-700 border-red-300',
  },
  viewing: {
    label: '보기',
    emoji: '🎬',
    color: 'bg-purple-100 text-purple-700 border-purple-300',
  },
  playing: {
    label: '놀기',
    emoji: '🕹️',
    color: 'bg-green-100 text-green-700 border-green-300',
  },
  walking: {
    label: '걷기',
    emoji: '🚶',
    color: 'bg-blue-100 text-blue-700 border-blue-300',
  }
};

export const RECOMMENDED_PLACES: Place[] = [
  {
    id: 'rec-1',
    name: 'CGV 용산아이파크몰',
    description: '다양한 영화를 즐길 수 있는 현대적인 영화관',
    lat: 37.5303,
    lng: 126.9638,
    emoji: '🎬',
    category: '영화관',
    activityCategory: { main: ['viewing', 'playing'] },
  },
  {
    id: 'rec-2',
    name: '블루보틀 삼청점',
    description: '고즈넉한 한옥에서 즐기는 특별한 커피 경험',
    lat: 37.5873,
    lng: 126.9806,
    emoji: '☕',
    category: '카페',
    activityCategory: { main: ['eating', 'walking', 'viewing'] },
  },
  {
    id: 'rec-3',
    name: '쉐이크쉑 강남점',
    description: '미국 본토의 맛을 느낄 수 있는 인기 수제버거 맛집',
    lat: 37.4998,
    lng: 127.0278,
    emoji: '🍔',
    category: '음식점',
    activityCategory: { main: ['eating'] },
  },
  {
    id: 'rec-4',
    name: '팀랩 몰입형 미디어아트 전시관',
    description: '빛과 예술이 어우러진 환상적인 몰입형 미디어아트 전시',
    lat: 37.5451,
    lng: 127.0422,
    emoji: '🎨',
    category: '전시관',
    activityCategory: { main: ['viewing', 'playing'] },
  },
  {
    id: 'rec-5',
    name: '아크앤북 시청점',
    description: '책과 라이프스타일이 결합된 독특한 북카페 서점',
    lat: 37.5654,
    lng: 126.9790,
    emoji: '📚',
    category: '문화시설',
    activityCategory: { main: ['viewing', 'eating'] },
  },
  {
    id: 'rec-6',
    name: '젠틀몬스터 플래그십스토어 가로수길',
    description: '독특한 디자인의 안경과 선글라스를 만날 수 있는 핫플레이스',
    lat: 37.5215,
    lng: 127.0221,
    emoji: '👓',
    category: '쇼핑',
    activityCategory: { main: ['viewing', 'playing'] },
  },
  {
    id: 'rec-7',
    name: '남산 돈까스',
    description: '남산의 명물, 바삭하고 두툼한 돈까스 전문점',
    lat: 37.5511,
    lng: 126.9870,
    emoji: '🍴',
    category: '음식점',
    activityCategory: { main: ['eating'] },
  },
  {
    id: 'rec-8',
    name: '국립현대미술관 서울관',
    description: '다양한 현대 미술 작품을 감상할 수 있는 미술관',
    lat: 37.5762,
    lng: 126.9800,
    emoji: '🖼️',
    category: '미술관',
    activityCategory: { main: ['viewing', 'walking'] },
  },
  {
    id: 'rec-9',
    name: '스타벅스 더종로점',
    description: '넓고 쾌적한 공간에서 다양한 음료와 디저트를 즐길 수 있는 대형 스타벅스',
    lat: 37.5701,
    lng: 126.9847,
    emoji: '☕',
    category: '카페',
    activityCategory: { main: ['eating', 'viewing', 'walking'] },
  },
  {
    id: 'rec-10',
    name: '방탈출 카페 코드케이 강남점',
    description: '친구들과 함께 즐거운 시간을 보낼 수 있는 인기 방탈출 카페',
    lat: 37.4984,
    lng: 127.0273,
    emoji: '🔑',
    category: '놀이',
    activityCategory: { main: ['playing'] },
  },
  {
    id: 'rec-11',
    name: '교보문고 광화문점',
    description: '다양한 서적과 문구류를 판매하는 대형 서점, 책 읽기 좋은 공간',
    lat: 37.5700,
    lng: 126.9774,
    emoji: '📚',
    category: '서점',
    activityCategory: { main: ['viewing', 'walking'] },
  },
  {
    id: 'rec-12',
    name: '호텔 델루나 세트장 (익선동)',
    description: '드라마 촬영지로 유명한 아름다운 한옥 골목, 포토존이 가득한 곳',
    lat: 37.5746,
    lng: 126.9901,
    emoji: '📸',
    category: '관광',
    activityCategory: { main: ['viewing', 'walking', 'eating'] },
  },
  {
    id: 'rec-13',
    name: '더현대서울',
    description: 'MZ세대에게 인기 많은 현대적인 백화점, 쇼핑과 다양한 볼거리',
    lat: 37.5259,
    lng: 126.9288,
    emoji: '🛍️',
    category: '쇼핑',
    activityCategory: { main: ['playing', 'eating', 'walking', 'viewing'] },
  },
  {
    id: 'rec-14',
    name: '을지로 골목 맛집 (만선호프)',
    description: '힙지로의 대표적인 노포 호프집, 시원한 맥주와 맛있는 안주',
    lat: 37.5658,
    lng: 126.9912,
    emoji: '🍻',
    category: '음식점',
    activityCategory: { main: ['eating', 'playing', 'walking'] },
  },
  {
    id: 'rec-15',
    name: '서울식물원',
    description: '다양한 식물들을 만날 수 있는 도심 속 식물원, 산책하기 좋은 곳',
    lat: 37.5700,
    lng: 126.8286,
    emoji: '🌿',
    category: '자연',
    activityCategory: { main: ['viewing', 'walking'] },
  },
  {
    id: 'rec-16',
    name: '롯데월드 어드벤처',
    description: '다양한 어트랙션과 즐길 거리가 가득한 테마파크',
    lat: 37.5214,
    lng: 127.1009,
    emoji: '🎡',
    category: '놀이공원',
    activityCategory: { main: ['playing', 'viewing', 'eating'] },
  },
  {
    id: 'rec-17',
    name: 'N서울타워',
    description: '서울의 랜드마크, 아름다운 야경과 전망을 감상할 수 있는 곳',
    lat: 37.5512,
    lng: 126.9880,
    emoji: '🗼',
    category: '관광',
    activityCategory: { main: ['viewing', 'walking', 'eating'] },
  },
  {
    id: 'rec-18',
    name: '국립중앙박물관',
    description: '한국의 역사와 문화를 한눈에 볼 수 있는 박물관',
    lat: 37.5233,
    lng: 126.9790,
    emoji: '🏛️',
    category: '박물관',
    activityCategory: { main: ['viewing', 'walking'] },
  },
  {
    id: 'rec-19',
    name: '코엑스 스타필드 라이브러리',
    description: '수많은 책으로 가득한 아름다운 도서관, 휴식과 독서 공간',
    lat: 37.5100,
    lng: 127.0592,
    emoji: '📚',
    category: '문화시설',
    activityCategory: { main: ['viewing', 'eating'] },
  },
  {
    id: 'rec-20',
    name: '가로수길',
    description: '트렌디한 카페와 편집샵이 즐비한 거리, 쇼핑과 산책',
    lat: 37.5215,
    lng: 127.0221,
    emoji: '🛍️',
    category: '거리',
    activityCategory: { main: ['shopping', 'eating', 'walking', 'viewing'] },
  },
  {
    id: 'rec-21',
    name: '경복궁',
    description: '조선 시대 왕궁, 아름다운 건축물과 역사적 의미',
    lat: 37.5796,
    lng: 126.9769,
    emoji: '🏯',
    category: '궁궐',
    activityCategory: { main: ['viewing', 'walking'] },
  },
  {
    id: 'rec-22',
    name: '인사동 쌈지길',
    description: '한국 전통 공예품과 기념품을 만날 수 있는 문화 거리',
    lat: 37.5743,
    lng: 126.9862,
    emoji: '🏺',
    category: '거리',
    activityCategory: { main: ['shopping', 'eating', 'walking', 'viewing'] },
  },
  {
    id: 'rec-23',
    name: '청계천',
    description: '도심 속 힐링 공간, 산책 및 휴식',
    lat: 37.5691,
    lng: 127.0047,
    emoji: '🏞️',
    category: '자연',
    activityCategory: { main: ['walking', 'viewing'] },
  },
  {
    id: 'rec-24',
    name: '광장시장',
    description: '다양한 길거리 음식과 전통 시장 분위기',
    lat: 37.5700,
    lng: 126.9995,
    emoji: '🍜',
    category: '시장',
    activityCategory: { main: ['eating', 'shopping', 'viewing'] },
  },
  {
    id: 'rec-25',
    name: '동대문 디자인 플라자 (DDP)',
    description: '독특한 건축물과 다양한 전시, 디자인 행사',
    lat: 37.5660,
    lng: 127.0094,
    emoji: '✨',
    category: '문화시설',
    activityCategory: { main: ['viewing', 'shopping'] },
  },
  {
    id: 'rec-26',
    name: '이태원',
    description: '다국적 문화와 이국적인 분위기를 느낄 수 있는 거리',
    lat: 37.5345,
    lng: 126.9945,
    emoji: '🌍',
    category: '거리',
    activityCategory: { main: ['eating', 'playing', 'shopping', 'viewing'] },
  },
  {
    id: 'rec-27',
    name: '선유도공원',
    description: '한강의 경치를 즐길 수 있는 아름다운 공원, 산책 및 피크닉',
    lat: 37.5458,
    lng: 126.9023,
    emoji: '🌳',
    category: '공원',
    activityCategory: { main: ['walking', 'viewing'] },
  },
  {
    id: 'rec-28',
    name: '서울숲',
    description: '도심 속 넓은 숲, 피크닉, 자전거, 산책 등 다양한 활동',
    lat: 37.5447,
    lng: 127.0402,
    emoji: '🌲',
    category: '공원',
    activityCategory: { main: ['walking', 'playing', 'viewing'] },
  },
  {
    id: 'rec-29',
    name: '강남역',
    description: '쇼핑, 음식점, 유흥시설이 밀집한 서울의 대표적인 번화가',
    lat: 37.4981,
    lng: 127.0276,
    emoji: '🏙️',
    category: '상업지구',
    activityCategory: { main: ['eating', 'playing', 'shopping', 'viewing'] },
  },
  {
    id: 'rec-30',
    name: '명동',
    description: '쇼핑과 길거리 음식으로 유명한 국제적인 관광 명소',
    lat: 37.5610,
    lng: 126.9860,
    emoji: '🛍️',
    category: '상업지구',
    activityCategory: { main: ['eating', 'shopping', 'viewing'] },
  },
]; 